### ISSUE TITLE
Calculate log records time

### ISSUE THREAD

**Issue by Gxost** [amadare42/JsMushHelper#40]
Each log record contains minutes or hours since it happened. This number must be converted to UTC.

If number of minutes is displayed, simply substract it from current UTC time.

If number of hours is displayed, more data have to be collected to find precise number of minutes elapsed. Let's look at example:

1. Now is 15:00, some record is displayed as ocurred 1 hour ago. Then this record was logged in range 13:01 - 14:00 (15:00 minus 1h to 1h 59 minutes). Here accuracy is 1 hour (0 to 59 minutes).
2. Now is 15:15, the record is still displayed as appeared 1 hour ago. Then this record was logged in range 13:16 - 14:15 (15:15 minus 1h to 1h 59 minutes). But as we have previous data sample, we can use conjunction to make our assumptions more precise: 13:01 - 14:00 and 13:16 - 14:15 gives us 13:16 to 14:00. Here accuracy is 45 minutes.
3. Now is 15:22, the record is shown as logged 2 hours ago. Then this record was logged in range 12:23 - 13:22 (15:22 minus 2h to 2h 59 minutes). After conjunction: 13:16 to 14:00 and 12:23 - 13:22 gives us 13:16 - 13:22. Here accuracy is 7 minutes.

**Comment by amadare42** [comment]
Depend on #59
